version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portolio
    volumes:
      - .:/var/www
    ports:
      - 8000:8000
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    container_name: portolio-mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: portolio
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
